version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: igreja_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: igreja_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - igreja_network

volumes:
  postgres_data:

networks:
  igreja_network:
    driver: bridge
